appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dHupG/K37CM4eJ4bh+Ua4tL9LhZ6TjMxhY8E7LQRTCGYiKuhUqu7TfIuCjgObRXDaHo0tEiyauPr8RsYL4W1QkNqCVBk8s5Dt8/IIasJAeUBq5T0e+KkmMPJU0BNwZ9H2zzj/mjUbpqZwYKe8t3VWRplzheOceZzyB6Er9KJhbrbM6fCYNs0xhMTEOh/8E1tgjv8uzFwutTHoi2wTTdBFmLDB/TAR0WdPf2C62T4DZjj/8TqyeH4PRqfTCTUjlgCzn/F7IB235jxcLOYz0Sf5Dq10d38OfqmtFKDIuFEpPdG3kQ4togxezO2XbPYE1LtsU+Vim3R++Ya0Z8h5G6xtuuE0+s8DkbPtQ+0FjzXqkdJvLFxL6BS3FzWr9pmmJTE5+H1idlh/ElsEU4yZcBFJOvwE1qhaUrGg1Anm4K7CmNWrYYLOXS+fc5MV3iVag1WrXTukSia9Y0LiiIEVZC1clICXSy4d6PAWsy+l6OO2oigEHOfEibh37EHE9zpQNLhFT3mpqyQHN5vife4idPtdQFlijLxq14ra7Qe6eARtLpliVat6L4lGqOoStvLTBxoWA6e3ellG65fgkgiu3r8UCrb4BCVGggbUDuG1g1ixRnYkfHNO6UhKBz6h0xfMmROqb9BLFpBPsRSH0Ce84pyN4aL2USpAgBLlB0GS/ZEVLY=}
