travis:
  secure:
    BINSTAR_TOKEN: Qw+Z/K12Apd0WRJlB9ILp3MHvuc8cxuYZ0RPE3i0o/xfr9NvsjqOZCmEyILpadWaGimd7SeDFVvN2SqqpCh25+COFmVEDHAJPtWQsVwL3s3SfbgAUQ86EdgWc6XXtMf6ZINPfuTvHS9ZxJKYG/LAeXHQC3rWHIL7HfUN/uCHxaABBG8ESwP6ZxpuIIllIH8GNFMXgLLNn/wPqPPR/nh1rzBpIC9sCxI4Na4dpm9TxMhIncygKs77Q3zv7AH+fBYu6iMRGgKox6uRq67RtjaZDWXaDlJfubsJVQJOvhvUn7y7hIUXCUHBMzv5IrUlNUrkF8/GlGP9AnZ2jDG5QLxGfEhTIvSaaQboqcSB2hA9eaAzCkiZc8gAH3wQJgRvFqV3t2dn8NMGhJWrUBM8kVXvn5HM1mNfdCgOhZDEmUwJ7h1R5D7NFhjzLB8wSj4CE7WamhextWUuGfxeFkrpWgSLsv1RZh07XsTCshQhXiynth8H7TKO1OcEG3qyltV4GMpIh3HYcHEBa3OIsphXuMdbU0pSNBrlRHs2tKfshZ3MlyYENMTZsXLpGN/p1qJtgLovQNwKxBgnFXP5xhjYnkshjCVUTyGZiRmQPiHm5QOpVgsmJCmK7djrTpCVA4br5kx8F52k001xbxdVlJk5H6haZp8JUXU1K+e/OfROqvFfnRc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
